auto: true
permalink: /:title/
baseurl: /langliefleren
sass:
  style: compressed
  sass_dir: css/_scss
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      image: /assets/main_og.png
      logo: /assets/langliefleren_logo.png
      author: Natasja de Vries
      social:
        name: Natasja de Vries
        links:
         - https://www.instagram.com/langliefleren/
      locale: nl_NL