auto: true
permalink: /:title/
baseurl: /langliefleren
sass:
  style: compressed
  sass_dir: css/_scss
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      image: /assets/main_og.png